apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: dev-
resources:
  - ../../base
images:
  - name: raodyuthi6/clusterguard
    newTag: dev
replicas:
  - name: smart-log-analyzer
    count: 1